#!/bin/sh
set -e
if [ "$1" = "configure" ]; then
  if command -v systemctl >/dev/null 2>&1; then
    systemctl daemon-reload || true
    systemctl enable --now open-icmp-server.service || true
  fi
  if command -v setcap >/dev/null 2>&1; then
    setcap cap_net_raw+ep /usr/local/bin/open_icmp_server_c || true
  fi
fi
exit 0
