#!/bin/sh
set -e
if [ "$1" = "remove" ]; then
  if command -v systemctl >/dev/null 2>&1; then
    systemctl stop open-icmp-server.service || true
    systemctl disable open-icmp-server.service || true
  fi
fi
exit 0
